services:
    app:
        build: .
        command: node ./app/server.js
        restart: always
        environment:
            NODE_ENV: ${NODE_ENV:-development}
            PORT: 8080
            MONGODB_URI: mongodb://mongodb:27017/mailink
        depends_on:
            - mongodb
        ports:
            - '8080:8080'
        volumes:
            - .:/usr/src/app
            - ./node_modules:/home/nodejs/node_modules

    mongodb:
        image: mongo:8
        restart: always
        command: mongod
        ports:
            - '27017:27017'
